### ISSUE TITLE
icecc can't find stdio

### ISSUE THREAD

**Issue by rillian** [mystor/icecc-osx-moztor#1]
Icecc hasn't been working for me lately in the Vancouver office. Configure fails because it can't find `stdio.h`. Help debugging much appreciated; I thought everything was preprocessed before being sent over the network.

Host is a MacBook Pro with MacOS 10.12.1. Scheduler is running on Fedora 24, workers running Fedora 24 and 25.

Things which changed recently:
- Upgraded Mac from 10.11.
- Added Fedora 25 machine.
- Re-ran install script on mac to try using Fedora 25 machine as the scheduler.
- Ran uninstall script, followed by install script to point it back at the Fedora 24 scheduler.

The icemon programme shows all three hosts talking to the scheduler.

**Comment by rillian** [comment]
Output from `./mach build -j40`:

```
 0:12.97 DEBUG: configure:6256: checking for valid debug flags
 0:12.97 DEBUG: configure:6267: /usr/local/bin/ccache /Users/giles/.local/icecream/cc -std=gnu99 -c  -fno-strict-aliasing -g -Qunused-arguments  conftest.c 1>&5
 0:12.97 DEBUG: configure:6261:10: fatal error: 'stdio.h' file not found
 0:12.97 DEBUG: #include <stdio.h>
 0:12.97 DEBUG:          ^
 0:12.97 DEBUG: 1 error generated.
```

**Comment by rillian** [comment]
Stopping iceccd on either the Fedora 25 machine or the Fedora 24 machine doesn't make a difference, so I think the problem is local.

**Comment by rillian** [comment]
Builds from a linux client also work. Maybe something with xcode 8?

**Comment by mystor** [comment]
@mstange has been looking into the problems with icecream on the most recent OS X. Maybe try his branch here (https://github.com/mstange/icecc-osx-moztor) on the updated OS X computer?

I should probably add notes to the main document...

**Comment by rillian** [comment]
Re-running `xcode-select --install` resolved this issue for me. Seems this is necessary after upgrading to XCode 8, even though non-icecream command-line builds were working fine. Maybe add that to the README?
